#!/usr/bin/env python3
"""Minimal workflow generator (Pattern: extract → synthesize → save_to deliverable).

Replaces over-engineered SW1-SW5 pipeline for prompts where:
- Deliverable is a single file (or small set)
- Source material can be injected via shell cat
- No iteration / test loop required

Produces workflows matching the proven p12-minimal.yml pattern.

Usage:
    # 2-step (with source files)
    python3 scripts/meta-v6/generate-minimal.py \
        --prompt docs/.../prompt-X.md \
        --source /path/to/file1,/path/to/file2 \
        --deliverable /path/to/output.md \
        --model Qwen3-5-9B-Q4_K_M \
        --output /tmp/generated.yml

    # 1-step (no source files, pure generation)
    python3 scripts/meta-v6/generate-minimal.py \
        --prompt docs/.../prompt-X.md \
        --deliverable /path/to/output.md \
        --output /tmp/generated.yml
"""
from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path


SKELETON_HEADER = '''workflow_id: "{workflow_id}"
name: "{name}"
description: "Minimal workflow generated by generate-minimal.py"
version: "1.0.0"
schema_version: "2.0.0"

providers:
  llama_cpp_with_vulkan:
    config:
      host: localhost
      port: 8080

models:
  qwen35:
    name: "{model_name}"
    host:
      type: llama_cpp_with_vulkan

workflow_execution_strategy:
  memory:
    model_lifecycle:
      unload_unused: false

agentic_workflow:
  when:
    after_workflow:
      - log:
          to_file_path: "{run_dir}/workflow.log"
          event_fields: [workflow_id, total_steps, succeeded, failed]
          level: info

  steps:
'''


def make_shell_cat_command(files: list[str], separators: bool = True) -> str:
    """Build a shell command that concatenates multiple files with optional separators."""
    parts = []
    for i, f in enumerate(files):
        if separators and i > 0:
            parts.append(f"printf '\\n=== {Path(f).name} ===\\n'")
        parts.append(f"cat {shlex.quote(f)}")
    return " && ".join(parts)


def make_extract_step(
    step_id: str,
    prompt_path: str,
    source_files: list[str],
    run_dir: str,
    extract_path: str,
) -> str:
    """Step 1: inject prompt + source files, ask model to extract inventory."""
    inject_files = [prompt_path] + source_files
    cat_cmd = make_shell_cat_command(inject_files)

    file_list_desc = ", ".join(Path(f).name for f in source_files) if source_files else "(none)"

    prompt = f"""You are analyzing source materials for a task.

You will receive:
(1) The complete user request (with task specification)
(2) Source files: {file_list_desc}

Your job: Extract and structure ALL information from the source files that is
relevant to the user's task. Output a structured markdown inventory that the
next step will use to synthesize the final deliverable.

Format your output as a markdown document with sections relevant to the task.
Quote real lines from source files as evidence (with file:line references).

Rules:
- Do NOT refuse. Do NOT say "I cannot read files" — file contents are below.
- Do NOT emit commentary about what you "would do". DO the work.
- Quote real content. Cite file:line.

=== INJECTED CONTEXT (prompt + source files) ===
{{{{bookmarks.shell_output.stdout}}}}
"""

    return f'''    {step_id}:
      generative_entity: "${{models.qwen35}}"
      prompt: |
{chr(10).join("        " + line for line in prompt.splitlines())}
      model_overrides:
        temperature: 0.2
        max_tokens: 8192
      when:
        before_step_starts:
          - shell:
              command: "{cat_cmd}"
              args: []
              working_dir: "/home/jon/code/whitt-execution-engine"
              fail_on_error: true
        after_step_succeeds:
          - save_to:
              - "{extract_path}"
          - log:
              to_file_path: "{run_dir}/logs/{step_id}.log"
              event_fields: [step_name, duration_ms, total_tokens]
              level: info

'''


def make_synthesize_step(
    step_id: str,
    prev_step_id: str,
    extract_path: str,
    deliverable_path: str,
    run_dir: str,
    local_copy_path: str,
    task_guidance: str,
) -> str:
    """Step 2: synthesize deliverable from extracted inventory."""
    prompt = f"""You are producing the final deliverable.

You will receive (via injected context) a structured inventory extracted from
source files. Your job is to synthesize the final deliverable document.

Task guidance: {task_guidance}

Rules:
- Be exhaustive. Address every aspect of the task.
- Use the extracted evidence to ground claims. Cite real content.
- Do NOT refuse. Do NOT say "provide the files" — they were already provided.
- Do NOT emit planning text. Produce the actual deliverable.
- Output ONLY the final document content. No preamble, no closing remarks.

=== EXTRACTED INVENTORY (from previous step) ===
{{{{bookmarks.shell_output.stdout}}}}
"""

    return f'''    {step_id}:
      generative_entity: "${{models.qwen35}}"
      depends_on: [{prev_step_id}]
      prompt: |
{chr(10).join("        " + line for line in prompt.splitlines())}
      model_overrides:
        temperature: 0.3
        max_tokens: 16384
      when:
        before_step_starts:
          - shell:
              command: "cat {extract_path}"
              args: []
              working_dir: "/home/jon/code/whitt-execution-engine"
              fail_on_error: true
        after_step_succeeds:
          - save_to:
              - "{deliverable_path}"
              - "{local_copy_path}"
          - log:
              to_file_path: "{run_dir}/logs/{step_id}.log"
              event_fields: [step_name, duration_ms, total_tokens]
              level: info
'''


def make_single_step(
    step_id: str,
    prompt_path: str,
    deliverable_path: str,
    run_dir: str,
    local_copy_path: str,
    task_guidance: str,
) -> str:
    """1-step workflow: inject prompt → emit deliverable directly."""
    prompt = f"""You are producing the final deliverable for the user's task.

Task guidance: {task_guidance}

You will receive (via injected context) the complete user request.

Rules:
- Be exhaustive. Address every aspect of the task.
- Do NOT refuse. Do NOT say "I cannot read files" — file contents are below.
- Do NOT emit planning text. Produce the actual deliverable.
- Output ONLY the final document content. No preamble, no closing remarks.

=== USER REQUEST ===
{{{{bookmarks.shell_output.stdout}}}}
"""

    return f'''    {step_id}:
      generative_entity: "${{models.qwen35}}"
      prompt: |
{chr(10).join("        " + line for line in prompt.splitlines())}
      model_overrides:
        temperature: 0.3
        max_tokens: 16384
      when:
        before_step_starts:
          - shell:
              command: "cat {prompt_path}"
              args: []
              working_dir: "/home/jon/code/whitt-execution-engine"
              fail_on_error: true
        after_step_succeeds:
          - save_to:
              - "{deliverable_path}"
              - "{local_copy_path}"
          - log:
              to_file_path: "{run_dir}/logs/{step_id}.log"
              event_fields: [step_name, duration_ms, total_tokens]
              level: info
'''


def derive_workflow_id(prompt_path: str) -> str:
    """Derive workflow_id from prompt filename."""
    stem = Path(prompt_path).stem
    clean = "".join(c if c.isalnum() else "_" for c in stem).strip("_").lower()
    return f"minimal_{clean}"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--prompt", required=True, help="Path to prompt markdown file")
    p.add_argument("--source", default="", help="Comma-separated source files to inject")
    p.add_argument("--deliverable", required=True, help="Final deliverable target path")
    p.add_argument("--model", default="Qwen3-5-9B-Q4_K_M", help="Model name")
    p.add_argument("--output", required=True, help="Output workflow YAML path")
    p.add_argument("--run-id", default=None, help="Run ID for log paths")
    p.add_argument("--task-guidance", default="Synthesize the deliverable from the injected context.", help="Synthesis guidance")
    args = p.parse_args()

    prompt_path = args.prompt
    if not Path(prompt_path).is_absolute():
        prompt_path = str(Path.cwd() / prompt_path)

    source_files = [f.strip() for f in args.source.split(",") if f.strip()]
    for f in source_files:
        if not Path(f).exists():
            sys.stderr.write(f"error: source file not found: {f}\n")
            return 1

    if not Path(prompt_path).exists():
        sys.stderr.write(f"error: prompt file not found: {prompt_path}\n")
        return 1

    run_id = args.run_id or f"minimal-{Path(args.prompt).stem}-gen"
    run_dir = f"./docs/benchmarks/outputs/meta-workflow/{run_id}"

    workflow_id = derive_workflow_id(prompt_path)
    name = Path(prompt_path).stem.replace("-", " ").title()

    header = SKELETON_HEADER.format(
        workflow_id=workflow_id,
        name=name,
        model_name=args.model,
        run_dir=run_dir,
    )

    extract_path = f"{run_dir}/workspace/inventory.md"
    local_copy_path = f"{run_dir}/workspace/deliverable.md"

    if source_files:
        step1 = make_extract_step(
            step_id="step_1_extract",
            prompt_path=prompt_path,
            source_files=source_files,
            run_dir=run_dir,
            extract_path=extract_path,
        )
        step2 = make_synthesize_step(
            step_id="step_2_synthesize",
            prev_step_id="step_1_extract",
            extract_path=extract_path,
            deliverable_path=args.deliverable,
            run_dir=run_dir,
            local_copy_path=local_copy_path,
            task_guidance=args.task_guidance,
        )
        body = step1 + "\n" + step2
    else:
        step1 = make_single_step(
            step_id="step_1_generate",
            prompt_path=prompt_path,
            deliverable_path=args.deliverable,
            run_dir=run_dir,
            local_copy_path=local_copy_path,
            task_guidance=args.task_guidance,
        )
        body = step1

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + body, encoding="utf-8")

    sys.stderr.write(
        f"[generate-minimal] wrote {output_path} "
        f"({'2-step' if source_files else '1-step'}, model={args.model})\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
