#!/usr/bin/env python3
"""Tier-B extension pass: append per-case voice paragraphs to reach 300-400 words."""
import os, re, sys

BASE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "test-cases", "tier-B-350")

EXT = {
"case-B-001-action-items-from-one-meeting-doc.md":
 "one more pass on quality since extraction is where these jobs go soft: an action item only counts if it has a doer and a thing to do, a sentence like we should revisit pricing is a wish, not an item, put wishes in a separate parking-lot list instead of pretending they're actionable. and decisions only count as decisions when they're settled, anything with we'll see or next time energy goes to open questions, not decisions. at the end paste the action table in chat, and flag any owner who walked away with more than three items, because that's how meetings quietly fail a week later.",
"case-B-002-csv-column-stats.md":
 "and a couple of notes so the profiler doesn't flatter itself: means and sigmas get computed on the non-null values only, but the null count is what justifies that, so both numbers appear together, always. the median for even counts, state your interpolation rule, don't make me guess. and the near-constant rule needs a real threshold, i said 90 percent same value in the fixture, your rule should catch that with margin, not exactly at the boundary, because a rule that only fires on the exact number i planted is a rule tuned to the demo, not the data.",
"case-B-003-json-config-linter.md":
 "on strictness: the linter fails closed, anything it can't classify is an error, not a warning, because configs that half-parse are worse than configs that don't. duplicate keys at the same level, last-wins is what parsers do, but i want it flagged loudly with both values shown, since silent last-wins is how a config slowly lies. and the report ends with a one-line verdict per file, clean, warnings only, or errors, so a skim of ten files takes ten seconds. paste the verdict lines in chat when done, plus the count of planted defects found versus planted, since i'm telling you they're in there.",
"case-B-004-error-windows-in-a-service-log.md":
 "and make the windows honest: a window is defined by a gap threshold, no error for n minutes ends the window, and that threshold goes in a rules note with a one-line justification, because window size is the whole game in this kind of analysis and i want to see the dial, not just the output. also count standalone errors, ones too lonely to form a window, they go in the report too, since a scatter of single failures sometimes matters more than the bursts. paste the top three windows in chat with their counts, and say plainly whether the after-midnight pattern held up or i imagined it.",
"case-B-005-duplicate-file-finder-by-content.md":
 "since content is the identity here, hashing is the obvious move, but say which hash and chunk it if the files get big, don't load everything into memory like it's 1995. and the group listing should be sorted by group size descending, biggest offenders first, because the one group of eight files is the finding, the forty pairs of two are noise. also compute the wasted bytes number, total size of redundant copies, since that's the number that justifies actually deleting things later. paste the top five groups in chat with sizes, and note any file that couldn't be read and why, rather than quietly skipping it.",
"case-B-006-markdown-table-repair.md":
 "and repair means conservative: fix the structure, never the content, a cell says what it says even if it looks wrong, you flag weird cells in the report instead of editing values. the repaired table must parse clean under a strict column-count check, every row same width, header separated properly, that check is the verifier and it runs on the output. keep an original copy untouched, the whole thing works on a copy so nothing destructive can happen even in theory. paste the before and after row counts plus the defect list in chat, and if a table is too far gone to save, say so and quarantine it instead of mangling it worse.",
"case-B-007-fuzzy-name-dedupe-for-a-guest-list.md":
 "on the fuzzy part: state the similarity measure and the threshold before you cluster anything, then show the threshold's effect by listing what merges at 0.85 versus 0.95, because one number is a decision and two numbers are a sensitivity analysis, and i always want the second. names with the same first initial but different surnames must never merge, that's a hard rule, put it in the rules file. and the final guest list keeps one canonical spelling per person, chosen by most frequent form, with the merged variants listed in the audit. paste the dedupe table in chat, the clusters with their variant spellings, so i can eyeball whether your fuzzy matched what my eyes would have.",
"case-B-008-cron-next-run-table.md":
 "parse strictly and fail loud, a schedule field that's seven entries or a day-of-week of 8 is a defect to report, not something to silently best-guess, because a wrong guess on a schedule is exactly the kind of error that pages someone at 3am later. support the standard five fields plus names for months and weekdays, mon and jan and so on, since real crontabs use them constantly. and the table gets sorted by next-run time ascending, soonest first, so it reads like an agenda. paste the top ten rows in chat, plus the list of any entries that failed to parse with the reason, and note the timezone assumption in a comment at the top of the table, since next run means nothing without it.",
"case-B-009-url-list-normalizer.md":
 "normalization order matters, so write it down: lowercase scheme and host, drop the default port, resolve dot segments, sort query params, strip fragments, and state whether trailing slashes stay or go, pick one and be consistent. the clash list is the important output, different originals mapping to one normalized form, grouped and counted, because that's the dedupe the whole exercise exists for. anything unparseable goes to a rejects list with the parse error quoted, not dropped. and the identity mapping file, original to normalized, is the audit trail, one line each, so any normalization decision can be checked against its input. paste the biggest clash groups in chat with the variant spellings that collapsed together.",
"case-B-010-weight-log-trend.md":
 "stats notes so the numbers stay honest: the trend is a simple least-squares slope over daily values, kilograms per week, stated with the units, not a mystery number. plateaus are runs of at least 14 consecutive days where the rolling 7-day mean moves less than 0.3 kilograms total, thresholds in the rules file where they belong. and the weekly summary table uses monday starts, say so, since week boundaries silently shift numbers when nobody declares them. the chart is ascii in the file, one row per week, because i want to open it in a terminal not launch a browser. paste the trend line verdict in chat, plain words, gaining, losing, or flat, with the slope number next to it.",
"case-B-011-budget-rollup.md":
 "arithmetic rules where the traps live: variances are computed against budget, not the other way, and they're signed, overspend positive, underspend negative, no absolute-value nonsense that hides direction. the rollup sums the categories, and the totals row gets checked against the sum of its parts to the cent, that's the verifier, integer cents throughout, no floats anywhere near money. movers are ranked by absolute variance but reported with the sign, so the biggest overspend and the biggest underspend are both visible, not just the loudest direction. and a one-line-per-category notes column for anything the data itself flags, a category over 150 percent of budget, say. paste the rollup table in chat and the totals-check result, since if that check fails nothing else in the report matters.",
"case-B-012-line-count-census-by-language.md":
 "classification notes: extension first, filename second, makefile and dockerfile by exact name since they have none worth trusting, and the unknown bucket exists precisely so nothing gets force-fit, a file that won't classify lands there with its name visible. comments and blanks are separate columns in the per-language table, code, comment, blank, total, since a language whose files are 80 percent comments is a different fact than raw lines. the per-extension breakdown underneath catches extension drift, two extensions mapping to one language and one extension claiming two. sort the summary by total lines descending, and paste it in chat along with the unknown list, because the unknowns are where i'll either nod or send you back.",
"case-B-013-yaml-duplicate-key-detector.md":
 "the detector reads yaml as text with real structure awareness, not just string matching, because a key appearing in two different mappings isn't a duplicate, only same-parent repeats count. report every duplicate with the path, the key, line numbers of both occurrences, and both values, since half the time the interesting question is which value wins. anchor and alias use doesn't count as duplication, that's yaml working as designed, don't flag it. the summary counts files scanned, files clean, files with duplicates, total duplicate instances, and the verifier is simple and strict: rescan confirms the same finding set, deterministic, byte-identical output on rerun. paste the findings table in chat, and flag any duplicate where the two values differ in type, not just value, since that's the one that bites hardest in production.",
"case-B-014-cidr-overlap.md":
 "expansion first, then analysis, and both get written to disk: the expanded host list per cidr, and then the overlap matrix, cidr by cidr, with the shared address count in each cell. the math is integer, addresses as 32-bit ints, no dotted-string arithmetic anywhere, because string tricks on ips are how off-by-ones sneak in. the containment special case gets its own flag, one cidr fully inside another is a different finding than a partial overlap, list both kinds separately. boundary cidrs like /31 and /32 must work, and the broadcast and network addresses count as real hosts here unless a rule says otherwise, so state the rule. paste the overlap pairs in chat with counts, and the verdict line on whether that suspicious containment exists or not.",
"case-B-015-word-frequency-with-stopwords.md":
 "tokenization rules stated up front: lowercase before counting, apostrophes stay inside words, hyphens split, digits count as words, and the stopword list is a visible file i can edit, not a buried constant, because stopword choice is an argument, not a fact. run the count twice, once raw and once stopped, and report both top-20 lists side by side, since the difference between them is itself a finding about the corpus. hapax legomena, words appearing exactly once, get a total count and a few examples, because a corpus's rare tail says things its headliners don't. paste the two lists in chat and one line on what the stopped list reveals that the raw one buries.",
"case-B-016-timestamp-normalizer.md":
 "the target format is iso 8601 utc, seconds precision, and every input form converts or gets quarantined, no silent drops, the rejects list quotes the original and the parse failure. two-digit years get a stated pivot rule, 26 is 2026 and 76 is 1976, write the rule down. the tz column in the output is the offset applied, so utc-plus-two originals show their move, and the format column names the input style, since the format census is half the value of this job. monotonicity is checked after normalization, out-of-order rows flagged, because that's usually where mixed-source data betrays itself. paste the format census in chat, count per input style, plus the rejects, and confirm the rerun is byte-identical.",
"case-B-017-quiz-grader.md":
 "grading rules pinned before any marking: exact string match after trim and case-fold, unanswered is blank is wrong, no partial credit, and multiple answers to one question takes the last, with the conflict logged. the answer key is a file, not code, so swapping keys reruns cleanly, and the per-question difficulty stat, fraction correct, finds the questions that fooled everyone. the score table shows raw score, percent, and letter by the stated cutoffs, 90, 80, 70, 60, and the cutoffs live in a config line i can change. verifier recomputes two scores by hand-logic independently and compares. paste the top of the leaderboard and the hardest three questions in chat, and note any student whose answers are byte-identical to another's, since that's a finding too.",
"case-B-018-photo-rename-plan.md":
 "the plan, not the execution, is the deliverable, generate it and do not move a single file: old path, new path, the extracted timestamp, and the camera it came from, one row each. zero-padded sequence numbers within a same-second burst, tie order by original filename so it's deterministic, and the sequence width stated so a hundred-shot burst doesn't break sorting later. files with no extractable timestamp go to a needs-review list with the reason, never a guessed date. collisions after rename, two cameras with bad clocks writing the same second, are detected and disambiguated by camera code in the new name, and that rule goes in the notes. paste the first ten rows of the plan in chat plus the needs-review count, and make the plan a csv so applying it later is one script away.",
"case-B-019-commit-stats-from-a-dump.md":
 "parse defensively, commit lines come in more shapes than the format claims, and anything that won't parse lands in a rejects file with the raw line quoted, counted in the report, not skipped. author normalization runs before stats, so the j. smith and john smith problem doesn't split one human into two rows, the mapping used goes in a notes file. business-hours means 9 to 5 local, weekday, and the after-hours percentage has its denominator in the report, total commits, since a percentage without its base is half a number. the punch-card grid is ascii, day rows by hour columns, and the busiest hour is called out in a sentence, not left for me to eyeball. paste the author table and the peak-hour line in chat.",
"case-B-020-text-diff-summary.md":
 "the summary is the deliverable, not the raw diff: counts first, added lines, removed, changed blocks, with changed defined as a delete-plus-add pair within a small window, definition stated. then the five biggest changes, each a one-line description with the hunk location, and the moved-block detection matters too, text deleted in one place and added in another is a move, not a change, and conflating them inflates the edit story. word-level stats supplement the line-level ones, since a one-word edit in a hundred-line paragraph is invisible to line diffs and that's exactly the edit that changes meaning. deterministic, rerun-stable, and paste the counts table plus the top-five changes in chat.",
}

def wordcount(t):
    return len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'\-.,;:()%]*", t))

def main():
    bad = 0
    for name, ext in sorted(EXT.items()):
        p = os.path.join(BASE, name)
        if not os.path.exists(p):
            print(f"MISSING {name}", file=sys.stderr); bad += 1; continue
        src = open(p).read().rstrip()
        w = wordcount(src)
        if w + wordcount(ext) > 400:
            print(f"SKIP {name}: already {w} + ext would exceed 400", file=sys.stderr); continue
        open(p, "w").write(src + "\n\n" + ext + "\n")
        print(f"{name}: {w} -> {w + wordcount(ext)}")
    files = sorted(os.listdir(BASE))
    print(f"total files: {len(files)}")
    ws = [wordcount(open(os.path.join(BASE, f)).read()) for f in files]
    print(f"word range now: {min(ws)}-{max(ws)}")
    out = [f for f, w in zip(files, ws) if not (300 <= w <= 400)]
    print("out of band:", out if out else "none")

if __name__ == "__main__":
    main()
